/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import tienda.Tienda;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import listaProductos.NodoProducto;
import clientes.Cliente;
import grafo.ResultadoDijkstra;

/**
 *
 * @author Ivannia Quesada
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Tienda tienda;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        tienda = new Tienda("Librería Online", "Costa Rica");
        
         setLocationRelativeTo(null); // CENTRAR VENTANA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Menú");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 118, 110));
        jLabel1.setText("MENÚ PRINCIPAL");

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jButton1.setBackground(new java.awt.Color(15, 118, 110));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(15, 118, 110));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Agregar ubicación");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(15, 118, 110));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mostrar inventario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(15, 118, 110));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Agregar conexión");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(15, 118, 110));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar cliente y comprar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(15, 118, 110));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Mostrar mapa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(15, 118, 110));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ver cliente al frente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(15, 118, 110));
        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(15, 118, 110));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Atender cliente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre del libro:");
        String categoria = JOptionPane.showInputDialog(this, "Categoría:");

        String id;

        while (true) {
            id = JOptionPane.showInputDialog(this, "ID:");

            if (id == null) {
                return;
            }

            if (tienda.buscarProducto(id) != null) {
                JOptionPane.showMessageDialog(this, "Error: ya existe un producto con ese ID");
            } else {
                break;
            }
        }

        double precio = Double.parseDouble(
                JOptionPane.showInputDialog(this, "Precio:")
        );

        int cantidad = Integer.parseInt(
                JOptionPane.showInputDialog(this, "Cantidad:")
        );

        ArrayList<String> imagenes = new ArrayList<>();

        int numImg = Integer.parseInt(
                JOptionPane.showInputDialog(this, "¿Cuántas imágenes desea agregar?")
        );

        for (int i = 0; i < numImg; i++) {
            String imagen = JOptionPane.showInputDialog(this, "Imagen " + (i + 1) + ":");
            imagenes.add(imagen);
        }

        NodoProducto producto = new NodoProducto(nombre, categoria, id, precio, cantidad, imagenes);
        tienda.agregarProducto(producto);

        JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String inventario = tienda.mostrarInventarioTexto();
        JOptionPane.showMessageDialog(this, inventario);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nombreCliente = JOptionPane.showInputDialog(this, "Nombre del cliente:");

        String idCliente;

        while (true) {
            idCliente = JOptionPane.showInputDialog(this, "ID del cliente:");

            if (idCliente == null) return;

            if (tienda.buscarClienteEnCola(idCliente) != null) {
                JOptionPane.showMessageDialog(this, "Error: ya existe un cliente con ese ID");
            } else {
                break;
            }
        }

        int prioridad = Integer.parseInt(
                JOptionPane.showInputDialog(this, "Prioridad (1 Básico, 2 Afiliado, 3 Premium):")
        );

        String ubicacion = JOptionPane.showInputDialog(this, "Ubicación del cliente:");

        // agregar ubicación al grafo
        tienda.agregarVertice(ubicacion);

        // crear cliente
        Cliente cliente = new Cliente(nombreCliente, idCliente, prioridad, ubicacion);

        // llenar carrito
        boolean agregarMas = true;

        while (agregarMas) {

            String idProducto = JOptionPane.showInputDialog(this, "ID del producto:");

            NodoProducto prod = tienda.buscarProducto(idProducto);

            if (prod == null) {
                JOptionPane.showMessageDialog(this, "Producto no encontrado");
            } else {

                int cant = Integer.parseInt(
                        JOptionPane.showInputDialog(this, "Cantidad:")
                );

                // validación de stock
                if (cant > prod.getCantidad()) {
                    JOptionPane.showMessageDialog(this, "No hay suficiente stock");
                    continue;
                }

                NodoProducto copia = new NodoProducto(
                        prod.getNombre(),
                        prod.getCategoria(),
                        prod.getId(),
                        prod.getPrecio(),
                        cant,
                        prod.getListaImagenes()
                );

                cliente.getCarrito().insertarNodoFInal(
                        copia.getNombre(),
                        copia.getCategoria(),
                        copia.getId(),
                        copia.getPrecio(),
                        copia.getCantidad(),
                        copia.getListaImagenes()
                );

                JOptionPane.showMessageDialog(this, "Producto agregado al carrito");
            }

            int resp = JOptionPane.showConfirmDialog(this, "¿Agregar otro producto?");
            if (resp != JOptionPane.YES_OPTION) {
                agregarMas = false;
            }
        }

        // agregar cliente a la cola
        tienda.agregarCliente(cliente);

        JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tienda.getColaClientes().estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay clientes en la cola");
            return;
        }

        Cliente cliente = tienda.getColaClientes().verFrente();
        
        String prioridadTexto;

        if (cliente.getPrioridad() == 1) {
            prioridadTexto = "Básico";
        } else if (cliente.getPrioridad() == 2) {
            prioridadTexto = "Afiliado";
        } else {
            prioridadTexto = "Premium";
        }

        String info = "Nombre: " + cliente.getNombre() +
                      "\nID: " + cliente.getIdCliente() +
                      "\nPrioridad: " + prioridadTexto +
                      "\nUbicación: " + cliente.getUbicacion();

        JOptionPane.showMessageDialog(this, info);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Cliente clienteFrente = tienda.getColaClientes().verFrente();

        if (clienteFrente == null) {
            JOptionPane.showMessageDialog(this, "No hay clientes en la cola para atender.");
            return;
        }

        if (!tienda.hayConexionConTienda(clienteFrente.getUbicacion())) {
            JOptionPane.showMessageDialog(this, "No se puede atender al cliente porque su ubicación está desconectada del mapa.");
            return;
        }

        Cliente atendido = tienda.atenderSiguienteCliente();

        if (atendido != null) {
            ResultadoDijkstra resultado = tienda.caminoMasCorto(atendido.getUbicacion());

            if (resultado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo calcular la ruta de entrega.");
                return;
            }

            String factura = tienda.generarFacturaTexto(atendido);

            String ruta =
                    "\n===== RUTA DE ENTREGA =====\n" +
                    "Origen: " + tienda.getUbicacion() + "\n" +
                    "Destino: " + atendido.getUbicacion() + "\n" +
                    "Camino más corto: " + resultado.getCamino() + "\n" +
                    "Distancia total: " + resultado.getDistanciaTotal() + " km\n";

            JOptionPane.showMessageDialog(this, factura + ruta);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String ubicacion = JOptionPane.showInputDialog(this, "Ingrese el nombre de la nueva ubicación:");

        if (ubicacion == null || ubicacion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La ubicación no puede estar vacía.");
            return;
        }

        tienda.agregarVertice(ubicacion);

        JOptionPane.showMessageDialog(this, "Ubicación agregada al mapa.");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String origen = JOptionPane.showInputDialog(this, "Ubicación de origen:");
        if (origen == null || origen.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una ubicación de origen válida.");
            return;
        }

        String destino = JOptionPane.showInputDialog(this, "Ubicación de destino:");
        if (destino == null || destino.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una ubicación de destino válida.");
            return;
        }

        String distanciaTexto = JOptionPane.showInputDialog(this, "Distancia entre ubicaciones:");
        if (distanciaTexto == null || distanciaTexto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una distancia.");
            return;
        }

        int distancia;

        try {
            distancia = Integer.parseInt(distanciaTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La distancia debe ser un número válido.");
            return;
        }

        tienda.agregarArista(origen, destino, distancia);

        JOptionPane.showMessageDialog(this, "Conexión agregada correctamente.");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String mapa = tienda.mostrarMapaTexto();
        JOptionPane.showMessageDialog(this, mapa);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Gracias por utilizar el servicio de Librería Online. Vuelve pronto...");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
